ALTER USER HR IDENTIFIED BY "&1";
ALTER USER OE IDENTIFIED BY "&1";
ALTER USER PM IDENTIFIED BY "&1";
ALTER USER IX IDENTIFIED BY "&1";
ALTER USER SH IDENTIFIED BY "&1";
ALTER USER BI IDENTIFIED BY "&1";